#!/bin/bash
#
# Create a Courseplay installable zip package from the branch passed in.
# <exclude file> is a file with patterns to exclude from the zip (see 'man zip')
#
# Usage:
#   packCourseplay <branch> <exclude file> <output file> <repo>
#
#       repo is relative to https://github.com/Courseplay
#
branch=$1
exclude_file=$2
output_file=$3
repo=$4

logger "Webhook from GitHub, packing $repo, branch $branch to $output_file"
cd /tmp
rm -rf ${repo}*
git clone --single-branch --depth 3 --branch "$branch" https://github.com/Courseplay/$repo
cd $repo
git checkout "$branch"

# extract version from modDesc.xml
grep '<version>' modDesc.xml | sed -e 's/<\/*version>//g' -e 's/^[ \t]*//'> /tmp/courseplay_version

rm -rf /tmp/${output_file}
zip -r /tmp/$output_file * --exclude @"$exclude_file"
