#!/bin/bash
#
# Create a Courseplay installable zip package from the branch passed in.
# <exclude file> is a file with patterns to exclude from the zip (see 'man zip')
#
# Usage:
#   packCourseplay <branch> <exclude file>
#
branch=$1
exclude_file=$2

logger "Webhook from GitHub, packing branch $branch"
cd /tmp
rm -rf courseplay*
git clone --single-branch --depth 3 --branch "$branch" https://github.com/Courseplay/courseplay
cd courseplay 
git checkout "$branch"

# extract version from modDesc.xml
grep '<version>' modDesc.xml | sed -e 's/<\/*version>//g' -e 's/^[ \t]*//'> /tmp/courseplay_version

filename=FS19_Courseplay.zip

echo $filename > /tmp/courseplay_filename
rm -rf /tmp/${filename}
zip -r /tmp/$filename * --exclude @"$exclude_file"
